baseURL: "https://rashmi-patel.github.io"
languageCode: "en-us"
title: "Rashmi Patel"
theme: master

Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/R.svg"

  theme:
    disableThemeToggle: false
    defaultTheme: "dark" # dark
    color:  
        secondaryBackgroundColor: "Blue"
    # darkmode:
    #     secondaryBackgroundColor: "Blue"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #     textColor: "black"
  #     secondaryTextColor: 
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
      position: absolute
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi there! I'm "
    title: "Rashmi Patel"
    #subtitle: 
    content: "I am a highly experienced Software Test engineer and Automation Test Architect with a distinguished track record of over 6 years in IT software development and testing. Currently I am pursuing my Master's in Computer Science from California State University, East Bay."
    image: "images/me_.jpeg"
    button:
      background - color: 
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/e/2PACX-1vSFOtOrrd__60oJ5raWEk6-L0tCAsiBP70m-OQiRTDRhuy_nFEEx4optrTDA4ndsYs3VWvQFP7IjOkb/pub"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/rashmi29
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/rashmi-p-patel/
        # - icon: fab fa-instagram
        #   url: https://www.instagram.com/
      #customIcons:
        #- icon: /fav.png
        #  url: "https://example.com"

  # About
  about:
    enable: true
    title: "I'm Open to work from December 2023"
    image: "/images/me1.jpg"
    content: 
     I am a highly experienced Software Test engineer and Automation Test Architect with a distinguished track record of over 6 years in IT software development and testing. I take immense satisfaction in meticulously crafting automation testing workflows that are designed to perfection, while consistently adhering to industry-leading frameworks and standards.
     Within my role, I excel in leading and coordinating automation testing projects, encompassing the full spectrum of activities from conceptualization to implementation. I possess an exceptional aptitude for designing and developing cutting-edge automation testing frameworks that cater to diverse functional and non-functional testing requirements. Furthermore, I possess a remarkable proficiency in seamlessly integrating manual testing teams into the automation workflow through the deployment of enterprise-level, industry-standard automation test frameworks.
     
    skills:
      enable: true
      title: "Skills:"
      items:
        - "Java, Python, C#, Typescript, Javascript, HTML, CSS"
        - "Selenium webdriver, Protractor, HP QTP, Rest Assured, Cypress, Appium"
        - Postman, Apache Jmeter, Tricentis Flood.IO
        - TestNG, Jasmine, MSTest, Cucumber
        - "MySQL, MongoDB"
        - Azure DevOps, Jira, HP Quality Center, Asana
        - Jenkins, AWS, Device Farm, Git, GitHub
        - MS Dynamics 365, Cascade CMS
        - Docker, Maven
        - Agile methedologies(Scrum), Waterfall
        - "Leadership, Mentorship, Multi-Cultural Fluency, Team Player"
       

  # Experience
  experience:
    enable: true
    items: 
      - job: "Software Test Engineer"
        company: "Rishabh software pvt. ltd."
        companyUrl: "https://www.rishabhsoft.com/"
        date: "Dec 2020 - Nov 2021"
        info:
          enable: true
          content: "Location: Gujarat, India "
        featuredLink:
          enable: false
          url: "https://www.rishabhsoft.com/"
        content: |-
          Gujarat, India
          - Designed and created automation framework using using selenium-webdriver, rest-assured, java, maven, TestNG, cucumber, resulting in 70% of testing time and 60% improvement in test coverage
          - Created azure devops build pipelines to execute automation regression suite on different browsers and environments
          - Analyze automation execution report, sharing report with executives and providing sign-off for release
          - Lead and worked as SPOC for common automation utilities initiative, did code review for all utilities
          - Gathered automation requirement from client, prepared automation POC and presented successful demo, resulted in gaining one new client for a company
          - Review pull request for automation script integration and provided feedback based on coding standards
          - Guided and supervised team members regarding a mobile application automation framework & script development using Appium and integration with AWS device farm
          - Empowered team members through comprehensive training on automation concepts, fostering enhanced proficiency and equipping them with advanced skill

      - job: "Senior Test Engineer"
        company: "Imriel technology solutions"
        companyUrl: "https://www.imriel.com"
        date: "Sep 2017 - Nov 2020"
        info:
          enable: true
          content: "Location: Gujarat, India"
        featuredLink:
          enable: false
          url: "https://www.imriel.com"
        info:
          content: 
        content: |-
          Gujarat, India
          - Conducted extensive functional and non-functional testing of web applications, designing and developing 300+ test cases, resulting in a defect detection rate of 85%
          - Collaborated with development and design teams to identify and report issues and defects, ensuring timely resolution and delivery of high-quality product
          - Developed regression suite for web application using selenium, C#, MSTest, reduced manual effort required by manual testing team
          - Designed and created postman and newman collections to automate REST API testing, leading to a 60% reduction in testing time and increased test coverage
          - Designed and developed a web automation framework using Protractor, jasmine, typescript, nodeJS; achieving a 70% decrease in regression testing efforts and saving 50+ man-hours per release cycle
          - Employed git and github for effective version control and team collaboration, enhancing code management and project management
          - Created jenkins pipelines to execute automation regression suite and smoke suited on different browsers and environments
          - Deployed AI powered test automation dashboard reportportal on docker and integrated with automation framework
          - Prepared performance testing suite using Apache JMeter and Tricentis Flood.IO to monitor API performance, resulting in swift identification of issues arising under high load conditions
          - Planned and created automation test plan, provided test estimation and distributed tasks to team
          - Led a QA team of 5 members, providing guidance and mentoring, managing task distribution, resulting increase in team productivity and successful delivery of all projects
          - Performed functional testing of complex distributed systems, application programming interfaces, and web applications, identifying and resolving 150+ critical issues
          - Participated in sprint planning, scrum, retrospective meeting and other agile development ceremonies
          - Designed and implemented a web application automation framework using cypress for one of the online event platform
          - Demonstrated expertise in test artifacts design - Test plan, Test case, Requirement traceability matrix, Defect report, Release sign-off report
  
          
      - job: "Programmer Analyst"
        company: "Cognizant"
        companyUrl: "https://www.cognizant.com/"
        date: "Dec 2014 - Oct 2016"
        info:
          enable: true
          content: "Location: Pune, India "
        featuredLink:
          enable: false
          url: "https://www.cognizant.com/"
        content: |-
          Pune, India
          - Developed regression automation scripts for the testing of a large banking application using QTP, VB Script and HP ALM, resulting in an 70% reduction in manual testing effort
          - Collaborated in migration activity of existing BPT framework scripts to in-house keyword driven framework
          - Strategized and created a UFT script to test xml file data generated through ETL process with application, resulting in remarkable 80% reduction in manual testing effort and improved 85% in overall quality
          - Prepared a series of daily and weekly status reports used in decision making by senior executives
          - Executing large regression suited before release, analyzing results and providing report to manager



  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Masters in Computer Science"
        school:
          name: "California State University - East Bay"
          url: "https://www.csueastbay.edu/"
        date: "2022 - 2023"
        GPA: "4.0 out of 4.0"
        content: |-
            - Working as a Teaching assistant for CS-201 Computer Science II subject where I am teaching students C++ concepts, providing assessments and grading their assessment
            - Worked as Computer Science tutor for SCAA ( Student Center for Academic Achievement ) department where I helped student with their queries, taught concepts and prepared material for their convenience
            - Worked as Grader for CS-301 Programming language concepts where I graded student's go programming assignments
            - Course Work: Web Systems, Cybersecurity, Software Engineering, Operating Systems, System Design, Cloud Computing
      - title: "Bachelor of Engineering in Computer Engineering"
        school:
          name: "Gujarat Technological University"
          url: "https://www.gtu.ac.in/"
        date: "2010 - 2014"
        GPA: "8.49 out of 10"
        content: |- 


  #featuredLink:
  #enable: true
  #name: "My academic record"
  #url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    items:
      #- title: Smart India Hackathon 2020
       # content: Won 2nd place in Smart India Hackathon 2020 for developing a Smart Yoga Instructor with feedback using Deep Learning
        #url: "https://www.sih.gov.in"
      - title: Foundation Level Certificate in Software Testing - ISTQB
        content: Awarded certificate by International Software Testing Qualifications Board on 18th February 2017
        url: "https://drive.google.com/file/d/1nelK2L0HNypJ1L1WxGhemjcBBVkIIroU/view"
      - title: Grace Hopper Conference Scholar 2022
        content: Was selected as GHC scholar in 2022 for my achievements and interest in STEM.
      - title: Intermediate Software Engineering Cource - Codepath
        content: Completed codepath cource during summer 2022
        url: "https://drive.google.com/file/d/1of3UoLVBq_qJfZ8NuChNg5t_p2wFQMVP/view?usp=sharing"
      - title: Cisco CyberOps Associate cource completion
        content: holder of this student-level credential has a broad understanding of Security Operations
        url: "https://www.credly.com/badges/51be056c-3057-4c3e-ad2f-9ec85e3d083e?source=linked_in_profile"
      - title: Fundamentals of RPA with UiPath
        content: Has successfully completed full-day training workshop by CRG Solutions
        url: "https://drive.google.com/file/d/1pMwqiw75vn-DBVLixii9Az8EeoDHjPSf/view"

  # projects
  projects:
    enable: true
    items:
      - title: Web application automation framework - TDD
        content: This is hybrid automation framework which uses page object model and data-driven framework concepts. This can be used for small application to large applications. This follows Test Driven Development approach. Features - Common utilities, report integration, logger integration, test data management, cross browser testing
        image: /images/projects/Project1-Selenium-TDD.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/rashmi29/Selenium-AUT-Framework
        badges:
          - "Selenium-webdriver"
          - "TestNG"
          - "Java"
          - "Maven"
          - "Extent-report"
        links:
          #- icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/rashmi29/Selenium-AUT-Framework
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Web application automation framework - BDD
        content: This is hybrid automation framework which uses page object model and behaviour-driven framework concepts. This can be used for small application to large applications.  Features - Common utilities, feature files, report integration, logger integration, test data management, cross browser testing
        image: /images/projects/Project2-Selenium-BDD.png
        featured:
          # name: Click here to know more!
          # link: https://github.com/rashmi29/BDD_AUT_Framework
        badges:
          - "Selenium-webdriver"
          - "Cucumber"
          - "TestNG"
          - "Java"
          - "Maven"
          - "Extent-report"
        links:
          - icon: fab fa-github
            url: https://github.com/rashmi29/BDD_AUT_Framework

      - title: Web application automation - Protractor
        content: This is hybrid automation framework. This can be used to automate application developed using js based frontend frameworks like angular/reactjs to handle asynchronous behaviour properly.
        image: /images/projects/Project3-Protractor.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/rashmi29/Protractor-AUT-Framework
        badges:
          - "Protractor"
          - "Jasmine"
          - "Typescript"
          - "Nodejs"
          - "Angular"
        links:
          - icon: fab fa-github
            url: https://github.com/rashmi29/Protractor-AUT-Framework

      - title: Excel comparator project
        content: This project is created to test two excel files cell by cell. This compares each cell and mark it as red if cell value is not matching. This utility was developed to test 12 excel reports which were present in legacy application and were newly incorporated in angular web application.
        image: /images/projects/Project4-Excel.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/
        badges:
          - "C#"

        links:
          - icon: fab fa-github
            url: https://github.com/rashmi29/Excel-comparator-Project

      - title: RestAPI automation using Postman collections
        content: This project is to automate rest api testing using postman collection. This postman collections can be execute from commandline newman tool which execute all test cases written in 'Test' page and  get api status before each release.
        image: /images/projects/Project5-postman.png
        # featured:
        #   name: Click here to know more!
        #   link: https://github.com/
        badges:
          - "Postman"
          - "Newman"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/rashmi29/Postman-collection-practice

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: rashmippatel2909@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/rashmi29
      linkedin: https://www.linkedin.com/in/rashmi-p-patel/
    # twitter: https://twitter.com
      # instagram: https://www.instagram.com/
    # facebook: https://facebook.com
